### ISSUE TITLE
In HttpRouter strtok() returns 'false'

### ISSUE THREAD

**Issue by foDAz1** [therion86/framework#16]
In HttpRouter it may happen that $this->basePath and $this->requestUri are the same. Especially when binding legacy code.

The following call is then incorrect:
$requestPath = str_replace($this->basePath, '', $this->requestUri);
$this->requestPath = strtok($requestPath, '?'); 

$requestPath becomes an empty string and strtok($requestPath, '?') then returns 'false'.

**Comment by therion86** [comment]
This is the normal behavior of routing. Maybe you have to change the nginx or apache conf for this. Here is an example for nginx conf: 
`server {
	listen 80;

        location ~ \.php$ {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass framework-app:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
      }
      location / {
          try_files $uri $uri/ /index.php?$query_string;
          gzip_static on;
      }
}`
